# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc5c8a53347922d04bf16978c8eda13d"
name = "template app"
handle = "template-app-43"
application_url = "https://fruits-thee-gamecube-motorcycle.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fruits-thee-gamecube-motorcycle.trycloudflare.com/auth/callback",
  "https://fruits-thee-gamecube-motorcycle.trycloudflare.com/auth/shopify/callback",
  "https://fruits-thee-gamecube-motorcycle.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
